# Generated by Django 5.0.3 on 2024-03-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('ID_aprendiz', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('Programa_formacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aprendiz',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('ID_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=50, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('ID_instructor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('especialidad', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('ID_jornada', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'jornada',
            },
        ),
    ]
